# Generated by Django 2.0.12 on 2020-01-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='time',
            field=models.IntegerField(default=10),
        ),
    ]
